### ISSUE TITLE
xmap issue

### ISSUE THREAD

**Issue by nsankar** [keichi/kEDM#5]
Hello @keichi ,

I passed a 2D numpy  array to the xmap function as below. 

import kedm
import numpy as np

x = np.random.uniform(2,15,size=6000).astype('float32')
y = np.random.uniform(2,15,size=6000).astype('float32')
data = np.stack((x,y),axis=1)    
print(data.shape)
ccm = kedm.xmap(data)

I am getting a type error for this as shown below. Am I missing anything here?   Thanks in advance

![image](https://user-images.githubusercontent.com/431890/170686445-d649b217-490e-4786-9f39-29a83c6800b9.png)

**Comment by nsankar** [comment]
I also checked with the sample data : xmap_all_to_all_test_input.csv

ds = np.loadtxt('/content/sample_data/xmap_all_to_all_test_input.csv', delimiter=",",skiprows=1)
ccm = kedm.xmap(ds)

I get the same error as above

**Comment by keichi** [comment]
Hi @nsankar, you are missing the second argument `edims`. This is a list of optimal embedding dimensions for each time series,  and can be computed using `kedm.edim()`. See:

https://github.com/keichi/kEDM/blob/a38a878b3c7ae022ed67673ae7da5c15141e7020/python/tests/test_xmap.py#L12

**Comment by nsankar** [comment]
@keichi . Appreciate your quick response. Thanks.
