### ISSUE TITLE
corrcoef_state - correlation query w.r.t xmap

### ISSUE THREAD

**Issue by nsankar** [keichi/kEDM#6]
Sir,

This is a general query about corrcoef_state  used in xmap (CCM).
(1) Is it correct to understand that the function corrcoef_state is used to find the correlation between source to target time series data inputs in xmap ?

(2) since CCM can work in non-linear data relationships, will corrcoef_state's correlation calculation work with time-series data under nonlinear relationships?

I also have a related generic CCM question after a cross-map prediction using nearest neighbors on X|Y(m) and Y||X(m), can we use Pearson correlation to finally arrive at the CCM correlation under an assumption that X and Y may have a nonlinear relationship? 

Thanks in advance.

**Comment by keichi** [comment]
Hi @nsankar, `corrcoef_state` is a generic class used to calculate Pearson's correlation in parallel. It is nothing specific to EDM/CCM.

> (1) Is it correct to understand that the function corrcoef_state is used to find the correlation between source to target time series data inputs in xmap ?

We do not calculate the correlation between the source and target time series; that would be just cross correlation. We calculate the correlation between the target time series predicted using cross mapping and the actual (observed) target time series.

> (2) since CCM can work in non-linear data relationships, will corrcoef_state's correlation calculation work with time-series data under nonlinear relationships?

You can calculate the correlation between any linear or non-linear time series using corrcoef_state. However I assume what you want to do is CCM. In that case you need to use functions that implement the EDM algorithms (xmap, smap, etc.)

I did not understand your last question.

**Comment by nsankar** [comment]
@keichi Thanks for the response. I think I got it. Primarily my doubt was since pearson correlation is meant for linear relationships , I was wondering if it is appropriate to use it for a cross mapped scenario. But as I understand, it can work on correlation between the target time series predicted using cross mapping and the actual (observed) target time series..

**Comment by keichi** [comment]
I will close this issue for now. Feel free to reopen if you have further questions.
